### ISSUE TITLE
embedded ICC color profiles of PNG images are not detected during import

### ISSUE THREAD

**Issue by DerAndere1** [scribusproject/scribus#125] opened 2019-11-18 20:17 UTC
Version: Scribus 1.5.5 for Windows 10 64bit
The embedded ICC color profile of an imported raster image is not detected. This results in wrong interpretation of pixel values and wrong colors in display and export.

Steps to reproduce:

1. Set the desired default color profiles in 'File ->preferences -> color management'. Activate color management by default.  
2. Create a new Scribus document, make sure color management is activated. 
3. Create a new image frame (hotkey: T)
4. Right-click on the image frame and select 'load image'. Select a raster image (e.g. a 16 bit per channel PNG) that is stored on the harddrive with an **embedded ICC color profile that is different** from the profile chosen in 'File -> Document setup -> color management -> Document profiles:RGB images '  
5. Observe that Scribus applies the profile chosen in step 1 to the imported image which results in wrong colors.

**Observed behaviour:**

The color of the imported image is wrong due to the wrong profile assignment (step 5)

**Expected behaviour:**

Since imported images can have different embedded profiles, do not rely on a per-document setting 'color management:document profile:RGB images'. Instead, upon import, analyze each source image file for embedded color profile info and apply that embedded color profile. If no profile info is found, sRGB should be assumed. This would result in correctly displayed colors. 

**Work-around:** 
For each embedded raster image, do steps 6 to 7:
6. Extract the embedded color profile from the original source-image  and save the extracted profile to file (e.g. using image-magick or exif-tools), put the profile file into the profile folder of Scribus. 
7. In Scribus, right-click the imported raster image and select 'properties (F2)'. In section 'Image:color management:input profile' select the profile from step 6.

**Comment by aoloe** [comment] 2019-11-19 10:04
@DerAndere1 can you please provide a sample image?

if possible with screenshots of what you obtain and what scribus should do...

**Comment by DerAndere1** [comment] 2019-11-19 13:54
In the attached zip archive you find an Scribus document (.sla) where the first image is added according to steps 1-5 and the image below (displayed correctly is added using the work around (steps 6-7). 
[colomanagementtest.zip](https://github.com/scribusproject/scribus/files/3864028/colomanagem

The original source image is attached for reference: 
![linSRGB](https://user-images.githubusercontent.com/26200979/69151678-5fd2fd80-0adb-11ea-9fea-653bd3424059.PNG)
enttest.zip)

Artworks is licensed under a [Creative Commons Attribution 4.0](https://creativecommons.org/licenses/by/4.0/) license.
Attribution to "David Revoy, www.davidrevoy.com".

**Comment by aoloe** [comment] 2019-11-19 14:25
@DerAndere1 , i've opened a ticket in the official scribus bug tracker:

https://bugs.scribus.net/view.php?id=15957

**Comment by aoloe** [comment] 2019-11-20 07:50
as jghali wrote in the official ticket, the issue is that at this time scribus does not support icc profiles embedded in PNG images.

i changed the title of this ticket to match this information.

until scribus "fully" supports PNG images, you can use tiff or jpg images...

**Comment by DerAndere1** [comment] 2019-11-20 10:36
Thanks a lot for forwarding those infos. Tiff works fine. Looks like Scribus has the same limitation as A$obe Illustrator, so I will have to use perceptual 8bit images . I hope at some point Scribus supports embedding 16 bit images into PDF. The PDF1.5 standard and newer allows embedding of high bit-depths images.

**Comment by aoloe** [comment] 2019-11-20 12:43
There are little chances that this issue will be resolved soon. But it's now tracked in the official bug tracker.

I'm closing this ticket and let the "official" one open, hoping for the best : - )

**Closed by aoloe** 2019-11-20 12:43 UTC

**Comment by DerAndere1** [comment] 2020-07-11 18:23
Whooo, I downloaded the latest Scribus 1.5.6 SVN snapshot and that already contains the fix, specifically for PNG import. Thanks to everyone involved. I think this was a mayor step.
